// Generated by https://quicktype.io

export interface IDog {
  bred_for: string
  breed_group: string
  height: Eight
  id: number
  image: Image
  life_span: string
  name: string
  origin: string
  reference_image_id: string
  temperament: string
  weight: Eight
}

export interface Eight {
  imperial: string
  metric: string
}

export interface Image {
  height: number
  id: string
  url: string
  width: number
}
